[build-system]
build-backend = "setuptools.build_meta"
requires = ["setuptools"]

[project]
name = "comms_sdk"
version = "1.0.0"
authors = [{name = "Pahappa Limited", email = "systems@pahappa.com"}]
description = "EgoSMS Python SDK"
license = "MIT"
dependencies = ["requests"]
readme = "README.md"
